services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Softify\SyliusImojePlugin\:
    resource: '../../../src/*'
    exclude: '../../../src/{Entity,Migrations,Tests,Kernel.php}'

  softify.imoje_plugin.gateway_factory:
    class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
    arguments: [ Softify\SyliusImojePlugin\ImojeGatewayFactory ]
    tags:
      - { name: payum.gateway_factory_builder, factory: imoje }

  Softify\SyliusImojePlugin\Form\Type\ImojeGatewayConfigurationType:
    tags:
      - { name: sylius.gateway_configuration_type, type: imoje, label: 'softify.imoje_plugin.gateway_label' }
      - { name: form.type }

  softify.imoje_plugin.action.capture:
    class: Softify\SyliusImojePlugin\Action\CaptureAction
    public: true
    arguments:
      - '@softify.imoje_plugin.service.imoje_payment'
    tags:
      - { name: payum.action, factory: imoje, alias: payum.action.capture }

  softify.imoje_plugin.action.notify:
    class: Softify\SyliusImojePlugin\Action\NotifyAction
    public: true
    arguments:
      - '@softify.imoje_plugin.service.imoje_payment'
    tags:
      - { name: payum.action, factory: imoje, alias: payum.action.notify }

  softify.imoje_plugin.action.status:
    class: Softify\SyliusImojePlugin\Action\StatusAction
    public: true
    tags:
      - { name: payum.action, factory: imoje, alias: payum.action.status }

  softify.imoje_plugin.action.convert_payment:
    class: Softify\SyliusImojePlugin\Action\ConvertPaymentAction
    public: true
    tags:
      - { name: payum.action, factory: imoje, alias: payum.action.convert_payment }

  softify.imoje_plugin.action.payment_details:
    class: Softify\SyliusImojePlugin\Action\PaymentDetailsAction
    public: true
    tags:
      - { name: payum.action, factory: imoje, alias: payum.action.payment_details }

  Softify\SyliusImojePlugin\Serializer\IntDenormalize:
    arguments:
      - '@Symfony\Component\Serializer\Normalizer\ObjectNormalizer'
    tags:
      - { name: serializer.denormalizer }

  softify.imoje_plugin.service.imoje_payment:
    class: Softify\SyliusImojePlugin\Service\ImojePaymentService

  softify.imoje_plugin.service.token_factory:
    class: Softify\SyliusImojePlugin\Service\TokenFactoryFromRequestService
    arguments:
      $securityTokenRepository: '@sylius.repository.payment_security_token'
      $orderRepository: '@sylius.repository.order'

  Softify\SyliusImojePlugin\Controller\UnsafeNotifyController:
    arguments:
      - '@softify.imoje_plugin.service.token_factory'


